export type ConstantNameEnum =
  | "INTERMEDIARY_TAX"
  | "PAYMENT_TAX_PIX"
  | "MIN_ORDER_VALUE"
  | "DELIVERY_HANDLING_DAYS"
  | "PAYMENT_TIMEOUT_MINUTES"
  | "MAKER_ACCEPTANCE_DAYS"
  | "REFUND_DELAY_TOLERANCE_DAYS"
  | "CONFIRMATION_TIMEOUT_DAYS"
  | "NEW_DEADLINE_TIMEOUT_DAYS"
  | "ADMIN_NOTIFICATION_EMAIL";

export const ConstantName = {
  INTERMEDIARY_TAX: "INTERMEDIARY_TAX" as ConstantNameEnum,
  PAYMENT_TAX_PIX: "PAYMENT_TAX_PIX" as ConstantNameEnum,
  MIN_ORDER_VALUE: "MIN_ORDER_VALUE" as ConstantNameEnum,
  DELIVERY_HANDLING_DAYS: "DELIVERY_HANDLING_DAYS" as ConstantNameEnum,
  PAYMENT_TIMEOUT_MINUTES: "PAYMENT_TIMEOUT_MINUTES" as ConstantNameEnum,
  MAKER_ACCEPTANCE_DAYS: "MAKER_ACCEPTANCE_DAYS" as ConstantNameEnum,
  REFUND_DELAY_TOLERANCE_DAYS:
    "REFUND_DELAY_TOLERANCE_DAYS" as ConstantNameEnum,
  CONFIRMATION_TIMEOUT_DAYS: "CONFIRMATION_TIMEOUT_DAYS" as ConstantNameEnum,
  NEW_DEADLINE_TIMEOUT_DAYS: "NEW_DEADLINE_TIMEOUT_DAYS" as ConstantNameEnum,
  ADMIN_NOTIFICATION_EMAIL: "ADMIN_NOTIFICATION_EMAIL" as ConstantNameEnum,
};
